apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: nginx-rollout
  namespace: fleet-default
spec:
  ignore: {}
  resources:
  - content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-preview
      spec:
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
    name: nginx-preview.yaml
  - content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-active
      spec:
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
    name: nginx-active.yaml
  - content: |
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: nginx-rollout
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx
        strategy:
          blueGreen:
            activeService: nginx-active
            previewService: nginx-preview
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.19.10
              ports:
              - containerPort: 80
    name: nginx.yaml
  targetRestrictions:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
    ignore: {}
